agility/agility/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from user_profile.forms import UserRegistrationForm
from registration.views import register
from user_profile.forms import UserRegistrationForm
from django.contrib.auth import views as auth_views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('agility.views',
    # Examples:
    # url(r'^$', 'agility.views.home', name='home'),
    # url(r'^agility/', include('agility.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^editor/', include('editor.urls')),
    url(r'^accounts/register/$', register, {'backend': 'registration.backends.default.DefaultBackend','form_class': UserRegistrationForm}, name='registration_register'),
    url(r'^accounts/login/$',  auth_views.login, {'template_name': 'registration/login.html', 'extra_context': {'form_register': UserRegistrationForm()} }, name='auth_login'),
    url(r'^facebook/', include('django_facebook.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('user_profile.urls')),
    url(r'^', 'home', name='home'),
)

agility/editor/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('editor.views',
	url(r'^courses/my/$', 'my_courses', name='my_courses'),
	url(r'^courses/latests/$', 'latests_courses', name='latests_courses'),
	url(r'^courses/new/$', 'new_course', name='new_course'),
	url(r'^courses/edit/(.+)$', 'edit_course', name='edit_course'),
	url(r'^courses/view/(.+)$', 'view_course', name='view_course'),
	url(r'^courses/preview/(.+).png$', 'preview_course', name='preview_course'),
)

agility/editor/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
import datetime
from django.conf import settings
from django.core.urlresolvers import reverse

CHOICES_TYPE = {
	('4xteams', _('Teams x4')),
	('40x40', _('Normal 40x40')),
}

class Course(models.Model):
	user = models.ForeignKey(User, verbose_name=_('User'), blank=False, null=False)

	name = models.CharField(verbose_name=_('Name'), max_length=255, blank=False, null=False)
	type = models.CharField(verbose_name=_('Type'), max_length=10, choices=CHOICES_TYPE, null=False, blank=False, default='40x40')

	json = models.TextField(verbose_name=_('Course'))
	description = models.TextField(verbose_name=_('Description'), blank=True, null=True)
	preview = models.TextField(verbose_name=_('Preview'), blank=True, null=True)

	date_creation = models.DateTimeField(_('Date creation'), blank=True, null=True, default=datetime.datetime.now())

	def get_share_url(self):
		return '%s%s' % (settings.SITE_URL, reverse('view_course', args=[self.id, ])) 

agility/editor/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from models import Course
from django.utils.translation import ugettext_lazy as _

 
class CourseForm(ModelForm):
	class Meta:
		model = Course
		fields = ['name', 'type', 'json', 'description', 'preview']

agility/editor/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from models import Course
from django.contrib.auth import get_user
from forms import CourseForm
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth.decorators import login_required
import datetime

@login_required(login_url='/accounts/login/')
def my_courses(request):
    courses = Course.objects.filter(user=get_user(request)).order_by('-date_creation')
    return render_to_response('editor/my_courses.html',
          {
            'courses': courses,
          },
          context_instance=RequestContext(request))

def latests_courses(request):
    courses = Course.objects.all().order_by('-date_creation')[:21]
    return render_to_response('editor/latests_courses.html',
          {
            'courses': courses,
          },
          context_instance=RequestContext(request))


@login_required(login_url='/accounts/login/')
def new_course(request):
    if request.method == 'POST':
        form = CourseForm(request.POST)

        if form.is_valid():
            course = form.save(commit=False)
            course.user = request.user
            course.date_creation = datetime.datetime.now()
            course.save()

            return HttpResponseRedirect(reverse("edit_course", args=(course.id,)))
    else:
        form = CourseForm()
    return render_to_response('editor/edit_course.html',
          {
            'form': form,
          },
          context_instance=RequestContext(request))


@login_required(login_url='/accounts/login/')
def edit_course(request, course_id):
    course = Course.objects.get(id=course_id)

    if course.user != request.user:
       return HttpResponseRedirect(reverse("view_course", args=(course.id,)))

    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            form = CourseForm(request.POST, instance=course)
            course = form.save()
    else:
        form = CourseForm(instance=course)
    return render_to_response('editor/edit_course.html',
          {
            'form': form,
            'is_edit': True,
            'course': course,
          },
          context_instance=RequestContext(request))


def view_course(request, course_id):
    course = Course.objects.get(id=course_id)

    return render_to_response('editor/view_course.html',
          {
            'course': course,
          },
          context_instance=RequestContext(request))


def preview_course(request, course_id):
    import base64

    course = Course.objects.get(id=course_id)

    image_data = course.preview.partition('base64,')[2]
    binary = base64.b64decode(image_data)
    return HttpResponse(binary, mimetype='image/png')

agility/templates/editor/edit_course.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_head %}
    {% if is_edit %}
      <meta property="og:title" content="Agility Training: {{course.name}}" />
      <meta property="og:description" content="{{course.description}}" />

      <meta property="og:type" content="website" />
      <meta property="og:image" content="http://agility-training.fr/{% url preview_course course.id %}" />
      <meta property="og:url" content="http://agility-training.fr/{% url view_course course.id %}" />
    {% endif %}

    <script src="{{STATIC_URL}}agility/js/raphael-min.js"></script>
    <script src="{{STATIC_URL}}agility/js/raphael.export.js"></script>
    <script src="{{STATIC_URL}}agility/js/canvg/StackBlur.js"></script>
    <script src="{{STATIC_URL}}agility/js/canvg/rgbcolor.js"></script>
    <script src="{{STATIC_URL}}agility/js/canvg/canvg.js"></script>
    <script src="{{STATIC_URL}}agility/js/editor/editor.js"></script>

    <style>
      .form input {
        width: 70%;
      }
      .form textarea {
        width: 70%;
      }
    </style>
{% endblock %}

{% block title %}
    <center>
      {% if is_edit %}
        <h1 class="page_title">{%blocktrans%}Edit a course{%endblocktrans%}</h1>
      {% else %}
        <h1 class="page_title">{%blocktrans%}Create a new course{%endblocktrans%}</h1>
      {% endif %}
  </center>
{% endblock %}


{% block content_full %}
<div style="text-align:center;width:100%;">

    {% if form.errors %}
    <p class="errors">{%blocktrans%}Please correct the errors below:{%endblocktrans%} {{ form.non_field_errors }}</p>
    {% endif %}


    <canvas id="editor_canvas" style="display:none;"></canvas>
    <img id="editor_image" style="display:none;"></img>
    <canvas id="editor_canvas_image" style="display:none;" width="1000px" height="1000px"></canvas>
    <form method="post" action="" id="form">
      {% csrf_token %}
      {{form.json.as_hidden}}
      {{form.preview.as_hidden}}

      {% if is_edit %}
      <div style="float:right;min-height:50px;">&nbsp;
        <span class='st_facebook_large' displayText='Facebook'></span>
          <span class='st_twitter_large' displayText='Tweet'></span>
          <span class='st_googleplus_large' displayText='Google +'></span>
      </div>
      {% endif %}
      <table class="form" width="100%">
        {% if form.name.errors %}
          <tr>
            <td>{{form.name.errors}}</td>
          </tr>
        {% endif %}
        <tr>
          <td>* <b>{{form.name.label_tag}}: </b> {{form.name}}&nbsp;&nbsp;&nbsp;&nbsp;<b>{{form.type.label_tag}}: </b>{{form.type}}</td>
        </tr>
        {% if form.json.errors %}
          <tr>
            <td>{{form.json.errors}}</td>
          </tr>
        {% endif %}
      </table>
            <div id="editor" style="margin: 0 auto;-webkit-backface-visibility:hidden; -webkit-transform: translate3d(0,0,0);"></div></td>
        
      <table class="form" width="100%">
        <tr>
          <th style="text-align:center;">{{form.description.label_tag}}</th>
        </tr>
        {% if form.description.errors %}
          <tr>
            <td>{{form.description.errors}}</td>
          </tr>
        {% endif %}
        <tr>
          <td>{{form.description}}</td>
        </tr>
        {% if is_edit %}
        <tr>
          <td><b><label for="share_link">{% trans 'Share link' %}</label>: </b> <input id="share_link" type="text" name="share_link" value="{{course.get_share_url}}" maxlength="255"></td>
        </tr>
        {% endif %}

    

    </table>
    <br>
    <input type="submit" value="{%blocktrans%}Save the course{%endblocktrans%}" />
    </form>

</div>

        

<script>
    function get_size_from_type() {
      val = $('#id_type').val();
      new_width = editor.width;
      new_height = editor.height;

      if(val == '4xteams') {
        new_width = 2*4000;
        new_height = 2*4000;
      }
      if(val == '40x40') {
        new_width = 4000;
        new_height = 4000;
      }

      return [new_width, new_height];
    }
    $(function() {
      var editor;

      if($('#id_json').val() != '') {
        json = $('#id_json').val();
        json = eval("(" + json + ")");
        editor = editor_json_load('editor', json , "{{STATIC_URL}}agility/js/editor/images/", false);
      } else {
        new_ = get_size_from_type();
        new_width = new_[0];
        new_height = new_[1];

        editor = editor_create(
              holder_id = "editor", 
              width = new_width,
              height = new_height,
              static_path = "{{STATIC_URL}}agility/js/editor/images/",
              false
          );
      }
      resize();

      function resize() {
        val = $('#id_type').val();
        old_type_select = val;
        
        new_ = get_size_from_type();
        new_width = new_[0];
        new_height = new_[1];
        
        editor_resize(editor, new_width, new_height);
        $('#content').css('width', editor.width_px + 24);  
      }

      var old_type_select = $('#id_type').val();
      $('#id_type').change(function() {
        
        new_ = get_size_from_type();
        new_width = new_[0];
        new_height = new_[1];
        
        if( new_width < editor.width || new_height < editor.height) {
          $( "#dialog-resize-smaller" ).dialog('open');
        } else {
          resize();
        }
      });


      var submit = false;
      $('#form').submit(function() {
        if(!submit) {
          editor_unselect_all(editor);
          json = editor_json_get(editor);
          json = JSON.stringify(json);
          $('#id_json').val(json);

          var svg = editor.R.toSVG();
          canvg(document.getElementById('editor_canvas'), svg);
          setTimeout(function() {
            //recherche des min et max pour centrer sur le parcours
            bbox = editor_course_bbox_get(editor);

            var dataURL = document.getElementById('editor_canvas').toDataURL("image/png");
            document.getElementById("editor_image").src = dataURL;
            
            $('#editor_canvas_image').attr('width', bbox.width);
            $('#editor_canvas_image').attr('height', bbox.height);
            var c=document.getElementById("editor_canvas_image");
            var ctx=c.getContext("2d");
            ctx.drawImage(document.getElementById("editor_image"), 
              bbox.x, bbox.y, bbox.width, bbox.height,
              0, 0, bbox.width, bbox.height);
            

            // $('#editor_canvas_image').attr('width', editor.width_px - editor.toolbar_left_width - editor.toolbar_right_width);
            // $('#editor_canvas_image').attr('height', editor.height_px);
            // var c=document.getElementById("editor_canvas_image");
            // var ctx=c.getContext("2d");
            // ctx.drawImage(document.getElementById("editor_image"), 
            //   editor.toolbar_left_width, 0, editor.width_px - editor.toolbar_left_width - editor.toolbar_right_width, editor.height_px,
            //   0, 0, editor.width_px - editor.toolbar_left_width - editor.toolbar_right_width, editor.height_px);
            
            var dataURL = document.getElementById('editor_canvas_image').toDataURL("image/png");
            $('#id_preview').val(dataURL);
            $('#form').submit();
            submit = true;
          }, 100);
          return false;
        } else {
            return true;
          }
      });


      $( "#dialog-resize-smaller" ).dialog({
        modal: true,
        height: 250,
        width: 600,
        autoOpen: false,
        buttons: {
          "{% trans 'Cancel' %}": function() {
            $('#id_type').val(old_type_select);
            $( this ).dialog( "close" );
          },
          "{% trans 'Ok resize the field' %}": function() {
            $( this ).dialog( "close" );
            resize();
          }
        }
      });


    });
</script>


<div id="dialog-resize-smaller" title="&nbsp;" style="display:none;">
  <p>
    <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
    {% trans 'The new field size will be smaller than the current, all obstacles outside the new field will be deleted.' %}
  </p>
</div>

{% endblock %}

agility/templates/editor/latests_courses.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    <center>
    	<h1 class="page_title">{%blocktrans%}Latests courses{%endblocktrans%}</h1>
	</center>
{% endblock %}

{% block content %}

		<table class="courses_list">
			<tr><th></th><th></th><th></th></tr>
			{% for course in courses %}
				{% if forloop.counter0|divisibleby:3 and forloop.counter0 == 0 %}
					<tr>
				{% elif forloop.counter0|divisibleby:3 and forloop.revcounter > 0 %}
					</tr><tr>
				{% endif %}

				<td width="25%" data-course-id="{{course.id}}" rel="course">
					<a href="{% url view_course course.id %}">
						<img src="{{course.preview}}" height="250px">
					</a><br>
					<a href="{% url view_course course.id %}">
						{{course.name}}
					</a>
					| <a href="{% url view_course course.id %}">{{ course.user.get_full_name }}</a>
				</td>


				{% if forloop.revcounter == 0 %}
					</tr>
				{% endif %}
			{% endfor %}
		</table>

		<script>
		$('td[rel="course"]').click(function() {
			course_id = $(this).attr('data-course-id');
			document.location.href="{% url edit_course 'COURSE_ID' %}".replace('COURSE_ID', course_id);
		});
		</script>


{% endblock %}

agility/templates/editor/my_courses.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    <center>
    	<h1 class="page_title">{%blocktrans%}My courses{%endblocktrans%}</h1>
	</center>
{% endblock %}

{% block content %}

		<div style="text-align:right; width:100%;">
			<a class="button" href="{% url new_course %}">{% trans 'Create a new course' %}</a>
		</div>
		<br><br>

		<table class="courses_list">
			<tr><th></th><th></th><th></th></tr>
			{% for course in courses %}
				{% if forloop.counter0|divisibleby:3 and forloop.counter0 == 0 %}
					<tr>
				{% elif forloop.counter0|divisibleby:3 and forloop.revcounter > 0 %}
					</tr><tr>
				{% endif %}

				<td width="25%" data-course-id="{{course.id}}" rel="course">
					<a href="{% url edit_course course.id %}">
						<img src="{{course.preview}}" height="250px">
					</a><br>
					<a href="{% url edit_course course.id %}">
						{{course.name}}
					</a>
					| <a href="{% url view_course course.id %}">{% trans 'Image' %}</a>
				</td>


				{% if forloop.revcounter == 0 %}
					</tr>
				{% endif %}
			{% endfor %}
		</table>

		<script>
		$('td[rel="course"]').click(function() {
			course_id = $(this).attr('data-course-id');
			document.location.href="{% url edit_course 'COURSE_ID' %}".replace('COURSE_ID', course_id);
		});
		</script>


{% endblock %}

agility/templates/editor/preview_course.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Agility Training</title>
        <script src="{{STATIC_URL}}agility/js/jquery-1.11.1.min.js"></script>
        </head>
    <body style="margin:0px;padding:0px;">

		<img src="" id="editor_image">

		{{course.preview}}
		<script>
		    $(function() {
		      document.getElementById("editor_image").src = '{{course.preview}}';
		      #window.location.replace("{{course.preview}}");
		    });
		</script>

</body>
</html>

agility/templates/editor/view_course.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_head %}
    <meta property="og:title" content="Agility Training: {{course.name}}" />
    <meta property="og:description" content="{{course.description}}" />

    <meta property="og:type" content="website" />
    <meta property="og:image" content="http://agility-training.fr/{% url preview_course course.id %}" />

    <script src="{{STATIC_URL}}agility/js/raphael-min.js"></script>
    <script src="{{STATIC_URL}}agility/js/raphael.export.js"></script>
    <script src="{{STATIC_URL}}agility/js/canvg/StackBlur.js"></script>
    <script src="{{STATIC_URL}}agility/js/canvg/rgbcolor.js"></script>
    <script src="{{STATIC_URL}}agility/js/canvg/canvg.js"></script>
    <script src="{{STATIC_URL}}agility/js/editor/editor.js"></script>
{% endblock %}

{% block title %}
    <center>
        <h1 class="page_title">{{course.name}}</h1>
  </center>
{% endblock %}


{% block content_full %}

<table width="100%">
    <tr>
        <td>
            <div style="padding-left:20px;float:left;">
                <p>{% trans 'Author' %}: {{course.user.get_full_name}}
            </div>
        </td>
        <td>
            <div style="padding-left:20px;float:right;">
                <span class='st_facebook_large' displayText='Facebook'></span>
                <span class='st_twitter_large' displayText='Tweet'></span>
                <span class='st_googleplus_large' displayText='Google +'></span>
            </div>
        </td>
    </tr>
</table>

<div style="text-align:center;width:100%;">
  <img src="" id="editor_image">
</div>
<div style="padding-left:20px">
    <p>{{course.description}}</p>
</div>

<div style="padding-left:20px">
    <p><label for="share_link">{% trans 'Share link' %}</label>: </b> <input style="width:70%" id="share_link" type="text" name="share_link" value="{{course.get_share_url}}" maxlength="255"></p>
</div>
        

<script>
    $(function() {
      document.getElementById("editor_image").src = '{{course.preview}}';
    });
</script>

{% endblock %}